# Generated by Django 5.2.7 on 2025-11-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gesicom', '0002_envio_rol_instructor_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='nombre',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='envio',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='envio',
            name='proyecto',
            field=models.CharField(blank=True, choices=[('LEM', 'LEM'), ('GIVIT', 'GIVIT'), ('ACAF', 'ACAF'), ('DEPOS', 'DEPOS'), ('IFPI', 'IFPI'), ('TUGA', 'TUGA')], max_length=20),
        ),
    ]
