# Generated by Django 5.2.8 on 2026-02-15 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de Restablecimiento',
                'verbose_name_plural': 'Tokens de Restablecimiento',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='cuentas_pas_token_847c78_idx'), models.Index(fields=['expires_at', 'used'], name='cuentas_pas_expires_f6557c_idx')],
            },
        ),
    ]
