"""
Django settings for SENNOVA project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xjv@=pz08182&5z4y-5o*&!xl&na@yg#str+@u6--2&p_=&8s*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Gesicom',
    'Usuarios.apps.UsuariosConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SENNOVA.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SENNOVA.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'Gesicom.validators.EightCharUpperNumberOrSpecialValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Media (uploads de archivos de evidencias)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Email backend
# If EMAIL_HOST_USER is set in environment, use SMTP; otherwise, console backend
if os.environ.get('EMAIL_HOST_USER'):
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    _user = os.environ.get('EMAIL_HOST_USER')
    _domain = (_user.split('@')[-1] if '@' in _user else '').lower()
    _providers = {
        'gmail.com': {'host': 'smtp.gmail.com', 'port': 587, 'tls': True},
        'outlook.com': {'host': 'smtp.office365.com', 'port': 587, 'tls': True},
        'hotmail.com': {'host': 'smtp.office365.com', 'port': 587, 'tls': True},
        'live.com': {'host': 'smtp.office365.com', 'port': 587, 'tls': True},
        'yahoo.com': {'host': 'smtp.mail.yahoo.com', 'port': 587, 'tls': True},
        'yahoo.es': {'host': 'smtp.mail.yahoo.com', 'port': 587, 'tls': True},
        'icloud.com': {'host': 'smtp.mail.me.com', 'port': 587, 'tls': True},
        'zoho.com': {'host': 'smtp.zoho.com', 'port': 587, 'tls': True},
        'proton.me': {'host': 'smtp.protonmail.ch', 'port': 587, 'tls': True},
        'protonmail.com': {'host': 'smtp.protonmail.ch', 'port': 587, 'tls': True},
    }
    _env_host = os.environ.get('EMAIL_HOST')
    _env_port = os.environ.get('EMAIL_PORT')
    _env_tls = os.environ.get('EMAIL_USE_TLS')
    _env_ssl = os.environ.get('EMAIL_USE_SSL')
    _cfg = _providers.get(_domain)
    _host = _env_host or (_cfg['host'] if _cfg else 'smtp.gmail.com')
    _port = int(_env_port or (_cfg['port'] if _cfg else 587))
    _tls = (_env_tls == 'True') if _env_tls is not None else ((_cfg['tls'] if _cfg else True))
    _ssl = (_env_ssl == 'True') if _env_ssl is not None else False
    if _ssl:
        _tls = False
    EMAIL_HOST = _host
    EMAIL_PORT = _port
    EMAIL_USE_TLS = _tls
    EMAIL_USE_SSL = _ssl
    EMAIL_HOST_USER = _user
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'no-reply@gesicom.local')

# Auth redirects
LOGIN_REDIRECT_URL = '/home/'
LOGOUT_REDIRECT_URL = '/login/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
