# Generated by Django 5.2.8 on 2025-11-11 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=60)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('contraseña', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rol', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('Persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gesicom.persona')),
            ],
        ),
    ]
