# Generated by Django 5.2.7 on 2025-11-11 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gesicom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evidencia', models.CharField(max_length=50)),
                ('link_evidencia', models.URLField(blank=True, null=True)),
                ('archivo_evidencia', models.FileField(blank=True, null=True, upload_to='evidencias/')),
                ('fecha_envio', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rol', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=60)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('contraseña', models.CharField(max_length=8)),
                ('Rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gesicom.roles')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=50)),
                ('Rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gesicom.roles')),
            ],
        ),
    ]
