# Generated by Django 5.2.8 on 2026-02-15 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gesicom', '0004_delete_rol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Perfil de Instructor',
                'verbose_name_plural': 'Perfiles de Instructores',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='Rol',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='Persona',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='Rol',
        ),
        migrations.AlterModelOptions(
            name='envio',
            options={'ordering': ['-fecha_envio'], 'verbose_name': 'Envío de Evidencia', 'verbose_name_plural': 'Envíos de Evidencia'},
        ),
        migrations.AddField(
            model_name='envio',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='envio',
            name='fecha_envio',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='envio',
            name='proyecto',
            field=models.CharField(blank=True, choices=[('LEM', 'LEM'), ('GIVIT', 'GIVIT'), ('ACAF', 'ACAF'), ('DEPOS', 'DEPOS'), ('IFPI', 'IFPI'), ('TUGA', 'TUGA')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='envio',
            index=models.Index(fields=['proyecto'], name='Gesicom_env_proyect_8521b8_idx'),
        ),
        migrations.AddIndex(
            model_name='envio',
            index=models.Index(fields=['fecha_envio'], name='Gesicom_env_fecha_e_d8683f_idx'),
        ),
        migrations.AddIndex(
            model_name='envio',
            index=models.Index(fields=['usuario', 'fecha_envio'], name='Gesicom_env_usuario_6759d1_idx'),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
