# Generated by Django 6.0.3 on 2026-03-04 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gesicom', '0004_delete_rol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rol',
            options={},
        ),
        migrations.AlterField(
            model_name='rol',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=80)),
                ('proyecto', models.CharField(blank=True, choices=[('LEM', 'LEM'), ('GIVIT', 'GIVIT'), ('ACAF', 'ACAF'), ('DEPOS', 'DEPOS'), ('IFPI', 'IFPI'), ('TUGA', 'TUGA')], max_length=20)),
                ('tipo_evidencia', models.CharField(max_length=50)),
                ('link_evidencia', models.URLField(blank=True, null=True)),
                ('archivo_evidencia', models.FileField(blank=True, null=True, upload_to='evidencias/')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_envio', models.DateField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
