# Generated by Django 6.0.2 on 2026-02-17 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gesicom', '0005_instructorprofile_rol_remove_instructor_rol_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='envio',
            options={'ordering': ['-fecha_envio']},
        ),
        migrations.AlterModelOptions(
            name='instructorprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='envio',
            name='Gesicom_env_proyect_8521b8_idx',
        ),
        migrations.RemoveIndex(
            model_name='envio',
            name='Gesicom_env_fecha_e_d8683f_idx',
        ),
        migrations.RemoveIndex(
            model_name='envio',
            name='Gesicom_env_usuario_6759d1_idx',
        ),
        migrations.AlterField(
            model_name='envio',
            name='fecha_envio',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='envio',
            name='proyecto',
            field=models.CharField(blank=True, choices=[('LEM', 'LEM'), ('GIVIT', 'GIVIT'), ('ACAF', 'ACAF'), ('DEPOS', 'DEPOS'), ('IFPI', 'IFPI'), ('TUGA', 'TUGA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
