# Generated by Django 5.2.8 on 2025-11-18 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gesicom', '0003_envio_nombre_envio_observaciones_envio_proyecto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
